#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE  24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

#define AUDIO_I2S_MIC_GPIO_SCK  GPIO_NUM_43
#define AUDIO_I2S_MIC_GPIO_DIN  GPIO_NUM_46

#define AUDIO_I2S_SPK_GPIO_BCLK GPIO_NUM_41
#define AUDIO_I2S_SPK_GPIO_WS   GPIO_NUM_43
#define AUDIO_I2S_SPK_GPIO_DOUT GPIO_NUM_42

#define AUDIO_CODEC_I2C_SDA_PIN  GPIO_NUM_NC
#define AUDIO_CODEC_I2C_SCL_PIN  GPIO_NUM_NC
#define AUDIO_CODEC_PA_PIN       GPIO_NUM_NC

#define BOOT_BUTTON_GPIO        GPIO_NUM_0
#define BUILTIN_LED_GPIO        GPIO_NUM_NC
#define VOLUME_UP_BUTTON_GPIO   GPIO_NUM_NC
#define VOLUME_DOWN_BUTTON_GPIO GPIO_NUM_NC

#define DISPLAY_WIDTH   240
#define DISPLAY_HEIGHT  135
#define DISPLAY_MIRROR_X true
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY true
#define DISPLAY_OFFSET_X  40
#define DISPLAY_OFFSET_Y  53

#define DISPLAY_SPI_MOSI_PIN GPIO_NUM_35
#define DISPLAY_SPI_SCLK_PIN GPIO_NUM_36
#define DISPLAY_SPI_CS_PIN   GPIO_NUM_37
#define DISPLAY_DC_PIN       GPIO_NUM_34
#define DISPLAY_RST_PIN      GPIO_NUM_33
#define DISPLAY_BACKLIGHT_PIN GPIO_NUM_38
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false

#define SD_CARD_MISO_PIN  GPIO_NUM_39
#define SD_CARD_MOSI_PIN  GPIO_NUM_14
#define SD_CARD_SCLK_PIN  GPIO_NUM_40
#define SD_CARD_CS_PIN    GPIO_NUM_12

#define BATTERY_ADC_PIN     GPIO_NUM_10
#define BATTERY_ADC_UNIT    ADC_UNIT_1
#define BATTERY_ADC_CHANNEL ADC1_CHANNEL_2

#define KEYBOARD_HC138_A0  GPIO_NUM_8
#define KEYBOARD_HC138_A1  GPIO_NUM_9
#define KEYBOARD_HC138_A2  GPIO_NUM_11

#endif
